### ISSUE TITLE
Check leaf absorbance

### ISSUE THREAD

**Issue by JulienLamour** [TESTgroup-BNL/LeafGasExchange#13]
Be sure that the light is not absorbed twice, once in the radiation model and once in the leaf level photosynthesis

**Comment by JulienLamour** [comment]
Checked for f.GPP, f.GPPT still has to be checked

**Comment by serbinsh** [comment]
I wonder if we can also make a unit test for the radiation calculations?  Seems ripe for that

[iphone]

On Feb 26, 2021, at 10:48, JulienLamour <notifications@github.com> wrote:

﻿

Checked for f.GPP, f.GPPT still has to be checked
