### ISSUE TITLE
Install error: BioCro not available for package LeafGasExchange

### ISSUE THREAD

**Issue by ginavong** [TESTgroup-BNL/LeafGasExchange#22]
I've been trying to install this package using the README instructions. Every time, I get an error about BioCro even though it is already installed and up-to-date. Don't know if I'm doing something wrong or if this is an issue with the package.
Thanks!

# Error message
```
ERROR: dependency 'BioCro' is not available for package 'LeafGasExchange'
* removing 'C:/Users/Serious Work/Documents/R/win-library/4.0/LeafGasExchange'
Warning messages:
1: In i.p(...) :
  installation of package ‘C:/Users/SERIOU~1/AppData/Local/Temp/RtmpsXK10x/file52b8626371af/BioCro_0.95.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/SERIOU~1/AppData/Local/Temp/RtmpsXK10x/file52b815f33912/LeafGasExchange_1.0.1.tar.gz’ had non-zero exit status
```

# Systems info
- Windows 10
- R v.4.0.2
- RStudio v.1.3.1093

**Comment by JulienLamour** [comment]
Sorry I didnt see your message earlier. I will check and probably remove the use of the package BioCro. Thks

**Comment by JulienLamour** [comment]
This should be corrected now
