### ISSUE TITLE
Rename package - before it starts getting widely used?

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/LeafGasExchange#7]
Given its beyond leaf, should we rename this package from here on out before its presented in a publication? Perhaps "CanopyFlux", "CanopyGasEx", "PlantGasExchange"?  or something of the like, not being very creative right now.  But as far as I can tell its gaining functionality that is beyond just leaf?  or not really because its modeling leaf then scaling up?

@neo0351 @regnans @DavidsonKen

**Comment by JulienLamour** [comment]
ForestCO2? ForestGasEx?

**Comment by alistairrogers** [comment]
I think PlantGasExchange is best, accurate but somewhat future proof for other applications in crops, grasslands, shrubs etc. Plant also avoids confusion with ecosystem fluxes (soil resp)

**Comment by serbinsh** [comment]
Great, thanks @alistairrogers (also sorry I meant to tag you here but seem to have not included you in the list??). @JulienLamour you OK with that?

**Comment by JulienLamour** [comment]
Yes that s fine
